USE [master]
GO

/****** Object:  Database [academia]    Script Date: 03/11/2022 1:45:19 ******/
DROP DATABASE [academia]
GO

/****** Object:  Database [academia]    Script Date: 03/11/2022 1:45:19 ******/
CREATE DATABASE [academia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'academia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\academia.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'academia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\academia_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [academia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [academia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [academia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [academia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [academia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [academia] SET ARITHABORT OFF 
GO

ALTER DATABASE [academia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [academia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [academia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [academia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [academia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [academia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [academia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [academia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [academia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [academia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [academia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [academia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [academia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [academia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [academia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [academia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [academia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [academia] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [academia] SET  MULTI_USER 
GO

ALTER DATABASE [academia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [academia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [academia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [academia] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [academia] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [academia] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [academia] SET QUERY_STORE = OFF
GO

ALTER DATABASE [academia] SET  READ_WRITE 
GO

